#!/bin/sh
HOOKS="pre-commit-prevent-master" # Add if needed pre-commit-rspec pre-commit-rubocop ...

for hook in $HOOKS; do
    if [ -f "$PWD/.githooks/$hook" ]; then
        "$PWD/.githooks/$hook"
        if [ $? != 0 ]; then
            exit 1
        fi
    else
        echo "Error: file $hook not found."
        exit 1
    fi
done
