apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: init # Refers to script that created it
  app: ${APP_NAME}
  env: ${OS_ENV}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-${OS_ENV}-secrets
  stringData:
    SECRET: ${SECRET} # Replace with own variables
parameters:
- description: Secret
  displayName: Secret
  name: SECRET
  required: true
- description: The Openshift environment
  displayName: The Openshift environment
  name: OS_ENV
  required: true
- description: The app name
  displayName: The app name
  name: APP_NAME
  required: true
